name: Combatter
author: ItsMas_

version: 1.6
main: me.mas.combatter.Combatter

commands:
  combatter:
    description: Combatter comand
    aliases: [cb]

  analyse:
    description: Used to analyse players