name: Combatter
author: ItsMas_

version: 1.2.1
main: me.mas.combatter.Combatter

commands:
  combatter:
    description: Combatter command
    aliases: [cb]

  analyse:
    description: Used to analyse players
