package me.mas.combatter.util;

public enum Message
{
    PREFIX,
    STARTED_ANALYSIS,
    ANALYSIS_FINISHED,
    NO_PERMS,
    ANALYSE_ARGS,
    PLAYER_NULL,
    NUMBER_INVALID,
    PLAYER_OFFLINE,
    ANALYSIS_NULL,
    ALREADY_ANALYSING,
    ALREADY_BEING_ANALYSED,
    RESULT
}
